### ISSUE TITLE
Missing domain names in sample data folder

### ISSUE THREAD

**Issue by vikramnitin9** [StanfordVL/taskonomy#21]
I noticed several of the target domain names from the configs in `taskbank/experiments/final` refer to folders that are missing (or differently named) in the [sample data folder](https://github.com/alexsax/taskonomy-sample-model-1) and in `data/README.md`.

For example, `curvature` doesn't have a data folder. The code takes the value of `cfg['target_domain_name']` directly and tries to access the folder of this name, which doesn't exist. So this gives an error while running training.

There are some domain names which have slightly different folder names. For example, `segmentsemantic` doesn't exist but `segment_semantic` exists. `keypoint2d` doesn't exist, but `keypoints2d` does.

Is there some preprocessing that needs to be done to this folder before running the code?

**Comment by alexsax** [comment]
There's no real preprocessing that needs to be done, but for the released data we tried to clean up some of the domain names (e.g. curvature -> principal_curvature). If you manage to get that TF code running, then I'd recommend just symlinking the user-friendly names back to whatever ugly name we used back when using that training code (e.g. `segmentsemantic` instead of `segment_semantic`)
