### ISSUE TITLE
It seems that Constraint II, Eq. (6) in Taskonomy paper will never be satisfied.

### ISSUE THREAD

**Issue by JerrikEph** [StanfordVL/taskonomy#7]
I have read you Taskonomy paper, and it's really cool.
I might be wrong, but It seems that Constraint II, Eq. (6) in Taskonomy paper will never be satisfied. 
<img width="499" alt="screen shot 2018-10-09 at 7 25 52 pm" src="https://user-images.githubusercontent.com/17830427/46666398-2dc54b80-cbf9-11e8-95fc-1af4891e86ca.png">

**Comment by qq456cvb** [comment]
This equation is also confusing me, how can positive products smaller than -1?

**Comment by amir32002** [comment]
you're looking at an old version of the paper that had a line in eq 6 missing. The version of the paper on the website ([link](http://taskonomy.stanford.edu/taskonomy_CVPR2018.pdf)) since last late year had that corrected (screenshot below). I intend to rewrite part of that section to be more intuitive and update arxiv too; in the meantime the visual illustration of the BIP constraints in slide 33 of [the presentation](https://storage.googleapis.com/taskonomy_slides/taskonomy_slides.html) might help with a more intuitive understanding.

<img width="650" alt="screen shot 2019-02-17 at 7 13 28 pm" src="https://user-images.githubusercontent.com/9710418/52925896-3ab12480-32e8-11e9-81e2-03805f2fff27.png">

**Comment by qq456cvb** [comment]
This makes sense, thank you

**Comment by tuvuumass** [comment]
I think $a_{|E| + j + 1}$ and $b_{|E| + j + 1}$ in the second line of Equation (6) should be $a_{|E| + |V| + j}$ and $b_{|E| + |V| + j}$, respectively.
