### ISSUE TITLE
what exactly does "supervision budget"mean?

### ISSUE THREAD

**Issue by emergencyd** [StanfordVL/taskonomy#9]
is that the maximum number of transfer order? then why is it assigned the name "supervision budget", since you already mentioned the order

**Comment by amir32002** [comment]
No, supervision budget is not transfer order. It is defined in the section 3 "Method", and figure 8 shows many samples. Supervision budget is the maximum number of source tasks that can be used in the solution. I.e. the maximum number of tasks that can be trained from scratch in order to solve the entire target set tasks. 

You can play with the API if you're looking for an intuitive understanding: http://taskonomy.stanford.edu/api/

**Comment by amir32002** [comment]
No, supervision budget is not transfer order. It is defined in the section 3 "Method", and figure 8 shows many samples. Supervision budget is the maximum number of source tasks that can be used in the solution. I.e. the maximum number of tasks that can be trained from scratch in order to solve the entire target set tasks.

You can play with the API if you're looking for an intuitive understanding: http://taskonomy.stanford.edu/api/
